version: 2

jobs:

    test:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: |
                pip install --user tox
                tox -vv

    integrate_rabbitmq:
        docker:
            - image: circleci/python:3.8
            - image: deadtrickster/rabbitmq_prometheus:3.7
        steps:
            - checkout
            - run:
                name: install dockerize
                command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
                environment:
                  DOCKERIZE_VERSION: v0.3.0
            - run: dockerize -wait tcp://localhost:5672 -timeout 1m # RabbitMQ
            - run: |
                pip install --user tox
                tox integration_tests/test_rabbitmq.py -vv

    integrate_pulsar:
        docker:
            - image: circleci/python:3.8
            - image: apachepulsar/pulsar:2.5.1
              command: bin/pulsar standalone
        steps:
            - checkout
            - run:
                name: install dockerize
                command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
                environment:
                  DOCKERIZE_VERSION: v0.3.0
            - run: dockerize -wait tcp://localhost:8080 -timeout 1m # Pulsar
            - run: dockerize -wait tcp://localhost:6650 -timeout 1m # Pulsar
            - run: |
                pip install --user tox
                tox integration_tests/test_apachepulsar.py -vv

    integrate_gcp:
        docker:
            - image: circleci/python:3.8
            # - image: gcr.io/google.com/cloudsdktool/cloud-sdk:344.0.0-emulators
              # command: gcloud beta emulators pubsub start
        steps:
            - checkout
            - run:
                name: install dockerize
                command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
                environment:
                  DOCKERIZE_VERSION: v0.3.0
            # - run: dockerize -wait tcp://localhost:8085 -timeout 1m # GCP
            - run: |
                pip install --user tox
                ./resources/gcp-install.sh
                gcloud beta emulators pubsub start --project="i3-gcp-proj" &
                tox integration_tests/test_gcp.py -vv

    examples:
        docker:
            - image: circleci/python:3.8
            - image: deadtrickster/rabbitmq_prometheus:3.7
            - image: apachepulsar/pulsar:2.5.1
              command: bin/pulsar standalone
            # - image: gcr.io/google.com/cloudsdktool/cloud-sdk:344.0.0-emulators
              # command: gcloud beta emulators pubsub start
        steps:
            - checkout
            - run:
                name: install dockerize
                command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
                environment:
                  DOCKERIZE_VERSION: v0.3.0
            - run: dockerize -wait tcp://localhost:5672 -timeout 1m # RabbitMQ
            - run: dockerize -wait tcp://localhost:8080 -timeout 1m # Pulsar
            - run: dockerize -wait tcp://localhost:6650 -timeout 1m # Pulsar
            # - run: dockerize -wait tcp://localhost:8085 -timeout 1m # GCP
            - run: |
                pip install --user tox
                tox --notest -vv
                . .tox/py/bin/activate
                echo "Now RabbitMQ..."
                ./examples/rabbitmq/run.sh
                echo "Now GCP..."
                ./resources/gcp-install.sh
                cd ./examples/gcp
                ./run-using-emulator.sh

workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - integrate_rabbitmq
            - integrate_pulsar
            - integrate_gcp
            - examples