version: 2
jobs:
    test:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: pip install tox && tox
workflows:
    version: 2
    build_and_test:
        jobs:
            - test
