version: 2
jobs:
    test:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: pip install --user tox && tox
    integrate:
        docker:
            - image: circleci/python:3.8
            - image: deadtrickster/rabbitmq_prometheus:3.7
        steps:
            - checkout
            - run: pip install --user tox && tox integration-tests
workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - integrate
