name: Add PR/Issue to Project

on:
  pull_request:
    types:
      - labeled
  issues:
    types:
      - labeled

permissions:
  contents: read
  actions: read
  pull-requests: read
  repository-projects: write

jobs:
  add-to-project:
    name: Add to Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/orgs/WIPACrepo/projects/6
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: dependencies
          label-operator: OR