name: Add PR/Issue to Project

on:
  pull_request:
    types:
      - labeled
  issues:
    types:
      - labeled

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: none
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  add-to-project:
    name: Add to Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/orgs/WIPACrepo/projects/6
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: dependencies
          label-operator: OR